### ISSUE TITLE
Error NU1101: Telerik.UI.for.Blazor.package not found

### ISSUE THREAD

**Issue by srgonzalez** [EdCharbeneau/BlazorBookExamples#2]
Hello @EdCharbeneau , how is it going?? 

I am getting this error when I try to run the Telerik project. I have tried several ways to add the package and reference to the project but none have worked. Could you please help me by indicating how I could do it? I am using VS Code. 

Thank you in advance

**Comment by EdCharbeneau** [comment]
This project requires a license for Telerik UI for Blazor. It is a bit old and could use an update. I will update the sample and convert it so it can use a Trial license which you can get for free at Telerik.com.

**Comment by srgonzalez** [comment]
Hi @EdCharbeneau , I used Visual Studio Community, and with this it was easier to test the Telerik templates. Thanks for your reply and for the ebook, it was very useful content.
